spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tenpo
    username: tenpo
    password: tenpo
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
app:
  jwt-secret: tenpo1234
  jwt-expiration: 12345678

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      calculatorClient:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


  retry:
    instances:
      calculatorClient:
        max-attempts: 2
        waitDuration: 1s

  ratelimiter:
    instances:
      calculatorClient:
        registerHealthIndicator: false
        limitForPeriod: 1
        limitRefreshPeriod: 30m
        timeoutDuration: 1s
